### ISSUE TITLE
Recommendation for changes or add requested item by experts

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#106]
Hi, 
Our Experts just let us know that the recommendation for changes or add requested item doesn't work anymore on the public view. It was working this morning since some experts did recommendations, but now they get a message saying : "Could not save recommended item : An unexpected error occurred"

See screenshot below : 
![image](https://user-images.githubusercontent.com/39295271/41606981-400eb3ba-73e5-11e8-8288-6446eae4a9b6.png)

**Comment by azanetti** [comment]
We are going to look at it tomorrow morning at the first hour.

**Comment by fabian** [comment]
I was able to reproduce this by recommending an addition without a potential supplier:

```
ERROR - GenericExceptionMapper     - Caught Exception
java.lang.NullPointerException
	at org.worldskills.api.il.rest.RecommendedItemResource.populateRecommendedItem(RecommendedItemResource.java:471)
	at org.worldskills.api.il.rest.RecommendedItemResource.addRecommendedItem(RecommendedItemResource.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:156)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fabian** [comment]
@ailtisWSFR  Axiocode made some changes on 20 June, did those changes fix the problem? Can we close this issue?

**Comment by ailtisWSFR** [comment]
@fabian No, the bug is still on, it hasn't fixed it, sorry.

**Comment by fabian** [comment]
@azanetti Can you check again if you can reproduce the problem?

**Comment by PierreAnctil** [comment]
@fabian I just tried to recommend an addition without potential supplier and that worked fine (despite an error message when selecting the supplied item : *Could not get supplied item: No access to view secret items*). I was also able to validate the recommendation and the new item appeared in the skill view. 

@ailtisWSFR can you reproduce the issue in staging? What skill and category are you using? What data are you recommending ?

**Comment by ailtisWSFR** [comment]
@PierreAnctil @fabian 
Please see video below regarding the bug on the production IL :

https://www.dropbox.com/s/wyrl8jgfvx8f3xh/Bug%20issue%20106%20LI%20.avi?dl=0 

In staging, it is working and I don't have the bug. This is probably because of changes made by @Joni-Aaltonen regarding issue #85 and pushed in staging. 
Do we have to wait for the deployment of issue #85 on production or dos the bug need to be fixed anyway before?

**Comment by fabian** [comment]
@ailtisWSFR I will deploy the changes from #85 to production this afternoon.

**Comment by ailtisWSFR** [comment]
@fabian @Joni-Aaltonen We still have the following bugs regarding issue #85  : 
 - An error message appears when clicking on the orange "recommend changes" button saying: "Could not get supplied item: No access to view secret items"
**- Information already saved about the "requested item"  (like "Description", Quantity" or "Potential supplier") not present in the field on the pop-up window to recommend changes, which is a big issue for us!** 

### We really need to fix those bugs before deploying the solution on production IL!

**Comment by fabian** [comment]
@ailtisWSFR With the changes from #85 now deploy on production do you still see this issue?

**Comment by ailtisWSFR** [comment]
@fabian Issue solved with the changes from # 85! I think that you can close this issue now. 
Thanks
